### ISSUE TITLE
React Konva Transformer above HTML element

### ISSUE THREAD

**Issue by harrysayers** [konvajs/react-konva-utils#36] opened 2024-09-18 19:01 UTC
Hello, I'm trying to get the React Konva transformer to appear above a HTML element as i'm using it to resize the HTML element. 

Here is what my component looks like

```
<Group>
  <html>
     <button/>
  </html>
</Group
<Transformer
   config
/>
```

I've tried setting the zIndex of the Html element using divProps however the HTML element is still appearing above the transformer. 

Any help is much appreciated. 

Thank you :)

**Comment by lavrton** [comment] 2024-09-18 19:43
That may be not simple to do. By design <Html /> component is just placed on top of the canvas with aboslute position.

There are some tricky workarounds to place HTML in between. You can take a look here: https://codesandbox.io/p/sandbox/react-konva-dom-between-konva-objects-dkrig1?file=%2Fsrc%2Findex.js

For now I dont' think it will be part of the library.

**Closed by lavrton** 2024-09-18 19:43 UTC

**Comment by harrysayers** [comment] 2024-09-19 07:45
Ah, thanks for the response! The demo workaround is not working for me.  Is there a way to change the position property of the transformer as absolute so it is on top of the html elements?

**Comment by harrysayers** [comment] 2024-09-19 14:35
@lavrton I also tried the demo you provided and it doesn't seem to work for me. 

Particularly this part (I replaced the refs with my refs)

```
 setTimeout(() => {
      const child = iframeRef.current.parentElement;
      const parent = stageRef.current.container();
      parent.removeChild(child);
      stageRef.current.content.prepend(child);
    }, 50);
```

I get "parentElement doesn't exist", "container isn't a function" or " removeChild is not a function" errors back. 

Thanks for your help. :)
